#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$ROOT_DIR/config"
CONFIG_FILE="$CONFIG_DIR/replayos.toml"
ENV_FILE="$ROOT_DIR/.env"

mkdir -p "$CONFIG_DIR" "$ROOT_DIR/data" "$ROOT_DIR/notes"

gen_key() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

echo "========================================"
echo "ReplayOS Setup Wizard"
echo "========================================"
echo "Choose provider API:"
echo "  1) Local Qwen (no external API key)"
echo "  2) Claude API"
echo "  3) OpenAI API"
read -r -p "Enter choice [1-3]: " CHOICE

PROVIDER=""
LOCAL_BASE_URL="http://localhost:11434"
LOCAL_MODEL="qwen2.5:7b-instruct-q4_K_M"
CLAUDE_MODEL="claude-sonnet-4"
OPENAI_MODEL="gpt-5-mini"
ANTHROPIC_API_KEY=""
OPENAI_API_KEY=""

case "$CHOICE" in
  1)
    PROVIDER="local_qwen"
    ;;
  2)
    PROVIDER="claude_api"
    read -r -s -p "ANTHROPIC_API_KEY: " ANTHROPIC_API_KEY
    echo ""
    if [[ -z "${ANTHROPIC_API_KEY// }" ]]; then
      echo "ANTHROPIC_API_KEY is required for Claude API."
      exit 1
    fi
    ;;
  3)
    PROVIDER="openai_api"
    read -r -s -p "OPENAI_API_KEY: " OPENAI_API_KEY
    echo ""
    if [[ -z "${OPENAI_API_KEY// }" ]]; then
      echo "OPENAI_API_KEY is required for OpenAI API."
      exit 1
    fi
    ;;
  *)
    echo "Invalid choice. Expected 1, 2, or 3."
    exit 1
    ;;
esac

REPLAYOS_API_KEY="$(gen_key)"

cat > "$CONFIG_FILE" <<CFG
[provider]
default = "$PROVIDER"

[provider.local_qwen]
base_url = "$LOCAL_BASE_URL"
model = "$LOCAL_MODEL"

[provider.claude_api]
model = "$CLAUDE_MODEL"

[provider.openai_api]
model = "$OPENAI_MODEL"

[safety]
require_ghost_run = true
require_approval_for_high_risk = true

[server]
host = "127.0.0.1"
port = 8787

[auth]
require_api_key = true
allow_localhost_without_key = false
api_keys = []

[limits]
max_request_bytes = 1048576
default_search_limit = 10
max_search_limit = 100
default_recent_limit = 20
max_recent_limit = 200
default_top_k = 5
max_top_k = 20
rate_limit_requests = 120
rate_limit_window_seconds = 60

[observability]
log_level = "INFO"
log_json = true

[runtime]
environment = "production"
provider_timeout_seconds = 60

[alerting]
error_rate_threshold = 0.20
error_window_seconds = 300
min_requests_for_alarm = 20

[data_policy]
default_retention_days = 30
allow_full_delete = false

[plugins]
directories = ["plugins"]
CFG

cat > "$ENV_FILE" <<ENV
# Generated by scripts/install.sh
REPLAYOS_API_KEYS=$REPLAYOS_API_KEY
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY
REPLAYOS_ENV=production
ENV

echo ""
echo "Wrote config: $CONFIG_FILE"
echo "Wrote env:    $ENV_FILE"

echo ""
echo "Running config check..."
python3 -m replayos.cli --config "$CONFIG_FILE" --env "$ENV_FILE" check

echo ""
echo "Setup complete."
echo "Start server with:"
echo "  python3 -m replayos.cli --config $CONFIG_FILE --env $ENV_FILE run"
echo ""
echo "ReplayOS API key (for /api/* calls):"
echo "  $REPLAYOS_API_KEY"
echo ""
echo "Use it as:"
echo "  Authorization: Bearer <key>"
